#!/bin/bash
source ./utils/helpers


ufw allow "OpenSSH" 
ufw --force enable
ufw --force reload
apt update -qq
apt upgrade -y -qq 

# apt install -y zsh -qq
# sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

source ./utils/install_certbot
source ./utils/check_system_requirements
source ./utils/install_postfix_dovecot
source ./utils/install_dkim_spf_spamassasin

#------------------------------------------------------------------------------------------------------------------------------
ufw --force reload

systemctl start postfix dovecot opendkim spamassassin
systemctl enable postfix dovecot opendkim spamassassin
systemctl restart postfix dovecot opendkim spamassassin

log_message "=======TESTING SETUP======="

sendmail -f $mail_root_user@$domain -t check-auth@verifier.port25.com << EOF
Subject: test from sendmail 
Hi there !!!
EOF

lastmail=$(ls -t /home/$mail_root_user/Maildir/cur | head -1)
sleep 20 && log_message "waiting 20 seconds for test results..." &&\
[[ -n $lastmail ]] &&\
awk '/Summary of Results/{flag=1} /Explanation/{flag=0} flag' /home/$mail_root_user/Maildir/cur/$lastmail