#!/bin/bash

# "Postfix Submission"
# "Postfix"
# "Dovecot Secure IMAP"

if [[ -n $1 ]];then 
  echo "Reading from configuration file $1"
  source $1
fi
force_read(){
  if [[ -z ${!2} ]];then
    local temp
    while [[ -z $temp ]];do
      read -p "$1:  " temp
    done
    eval $2=$temp
  fi
}
log_message(){
  if [[ $? -eq 0 ]];then
    printf "\e[0;32m \u2713 Success: $1 \e[0m \n"
  else
    printf "\e[0;31m \u2713 Failed: $1 \e[0m \n"
    exit 1
  fi
}

# Basic ubuntu setup
if [[ "$UID" -ne "0" ]];then
  log_message "Re-run this script as root"
  exit 1
fi
ufw allow "OpenSSH"
ufw --force reload

apt update -qq
apt upgrade -y -qq 

apt install python3-certbot-dns-digitalocean certbot -y -qq
force_read "digitalocean access token \nhttps://cloud.digitalocean.com/account/api/tokens   " digitalocean_token
rm ~/.certbot-creds.ini
echo "dns_digitalocean_token = $digitalocean_token" >> ~/.certbot-creds.ini
chmod 600 ~/.certbot-creds.ini
force_read "FQDN doamin.com " domain
force_read "webmaster email " webmaster

certbot certonly --agree-tos -m "$webmaster" --dns-digitalocean --dns-digitalocean-credentials ~/.certbot-creds.ini -d "*.$domain"
ssl_cert=/etc/letsencrypt/live/"$domain"/fullchain.pem
ssl_key=/etc/letsencrypt/live/"$domain"/privkey.pem

if [[ ! -f "${ssl_cert}" ]];then
  log_message "certbot didn not perform correctly" && exit 1
fi
certbot renew --dns-digitalocean --dns-digitalocean-credentials ~/.certbot-creds.ini --dns-digitalocean-propagation-seconds 60 --dry-run
if [[ $? -eq 0 ]];then
  sed -i".backup" /certbot/d /var/spool/cron/crontabs/root 
  echo "MAILTO=root,${webmaster}" >> /var/spool/cron/crontabs/root 
  echo "1 1 1 * * /usr/bin/certbot renew\
  --dns-digitalocean --dns-digitalocean-credentials ~/.certbot-creds.ini\
  --post-hook 'systemctl reload nginx'" >> /var/spool/cron/crontabs/root 

  log_message "=> SSL certificate is ready as auto renewal hook cronjob with alerts to webmaster email"
fi
#------------------------------------------------------------------------------------------------------------------------------
